### ISSUE TITLE
Cannot start

### ISSUE THREAD

**Issue by onlize** [nutechsoftware/ser2sock#11]
Hello,

I am trying to install it on my Raspberry Pi. I followed all installation steps, but the service could not start:

`pi@mypi:~/ser2sock $ sudo systemctl status ser2sock.service`
`ser2sock.service - LSB: init script for ser2sock instantiation`
`   Loaded: loaded (/etc/init.d/ser2sock; generated; vendor preset: enabled)`
`   Active: inactive (dead)`
`     Docs: man:systemd-sysv-generator(8)`
`pi@mypi:~/ser2sock $`

I tried to start it, but cannot:
`pi@mypi:~/ser2sock $ sudo /etc/init.d/ser2sock start`
``
`Starting instantiation ser2sock of ser2sock...`
``
`Script name       : ser2sock`
`Executable file   : /usr/local/bin/ser2sock`
`Arguments         : -d -f /etc/ser2sock/ser2sock.conf -P /var/run/ser2sock/ser2sock.pid`
`Configuration file: /etc/ser2sock/ser2sock.conf`
`PID file          : /var/run/ser2sock/ser2sock.pid`
``
`Failed to start - Return Value = 1`
``
`pi@mypi:~/ser2sock $`

Can you help?

**Comment by f34rdotcom** [comment]
Try directly from shell to see what i does.

/usr/local/bin/ser2sock-f /etc/ser2sock/ser2sock.conf -P
/var/run/ser2sock/ser2sock.pid

Best
Support @ AD2

**Comment by onlize** [comment]
Hello Sean,

I have this:

pi@alarmdecoder:~ $ /usr/local/bin/ser2sock-f /etc/ser2sock/ser2sock.conf -P
-bash: /usr/local/bin/ser2sock-f: No such file or directory
pi@alarmdecoder:~ $ /var/run/ser2sock/ser2sock.pid
-bash: /var/run/ser2sock/ser2sock.pid: No such file or directory
pi@alarmdecoder:~ $

Any ideas? I was using the image for my RPi that I downloaded from your website.

Thank you.
Igor Kravchenko.

________________________________

**Comment by f34rdotcom** [comment]
Sorry that was a TyPo... Needs a space between "ser2sock" and "-f"
 /usr/local/bin/ser2sock -f /etc/ser2sock/ser2sock.conf -P

**Comment by onlize** [comment]
Sean,

Here is the output:

pi@alarmdecoder:~ $ /usr/local/bin/ser2sock -f /etc/ser2sock/ser2sock.conf -P
ser2sock[867]: [✔] Using config file: /etc/ser2sock/ser2sock.conf
ser2sock[867]: [✔] Serial 2 Socket Relay version V1.5.2 starting
ser2sock[867]: [✘] Fatal error binding to server port 10000 errno: 98
ser2sock[867]: [✘] ERROR initializing listen socket :Address already in use
ser2sock[867]: [✘] exiting
pi@alarmdecoder:~ $

I already tried to use another SD card with the same image and I have exactly the same output.

Thank you.
Igor Kravchenko.
________________________________

**Comment by f34rdotcom** [comment]
Ok that indicates its running already. If you are running our image it already has ser2sock setup and you can configure it via the web interface of the AlarmDecoder webapp.
Or maybe its just a stuck process and needs to be killed first.

**Comment by onlize** [comment]
Sean,

Should I kill the process and run that web configuration utility?  What process should be killed and how to kill it?

I restarted my RPi multiple times when I tested, but always the same result. I always have this:
[cid:b0035678-fefc-4fd8-9841-5b217ddc48a6]


Thank you.
Igor Kravchenko.
________________________________

**Comment by f34rdotcom** [comment]
I would start with our stock image. Then power it up on your Pi with our AD2USB, Serial or Pihat attached.
connect to it locally http://alarmdecoder-local/ and run through the setup process. When asked to enable ser2sock that is ON by default just answer all the questions with no changes it should be all coorect except for your AD2* type. I am available for remote desktop support if you contact us on our email support or phone #

**Comment by onlize** [comment]
Sean,

I'd be happy to work with you on the phone and share my desktop. It will speed up the process. I am available now or any time today, if nothing urgent comes up with my work.

You can reach me at +13204346026, or I can call you if you want to. Just send me your phone number.

Thank you.
Igor Kravchenko.

________________________________

**Comment by onlize** [comment]
Sean,

Thank you for your call. As agreed, I tried another RPi and I have exactly the same issue.

My Order Number: 1499. Please let me know if need anything else for replacement.

If you still think that the card should be replaced, please send me another one. If not, let me know what can be done.

In any case, please let me know the next step.

Thank you.
Igor Kravchenko.

________________________________
