### ISSUE TITLE
Updated to work with openssl dev in arch linux

### ISSUE THREAD

**Issue by middleagedman** [nutechsoftware/ser2sock#9]
I don't know if this applies to other distributions, but I had to modify the configure files in order to compile against openssl

sed -i s/SSL_library_init/OPENSSL_init_ssl/ configure.ac configure

I found this blurb on the net concerning another package with the same compile issue:

However, in openssl 1.1, SSL_library_init is a preprocessor macro, not an actual symbol; so libesmtp's ./configure erroneously thinks that libssl isn't available, and disables openssl support.

**Comment by middleagedman** [comment]
FYI.. Users can also use this systemd file to start/stop service.  

Just place in /etc/systemd/system/ser2sock.service
Run 'systemctl daemon-reload'
Run 'systemctl enable ser2sock.service'
Run 'systemctl start ser2sock.service'


```
[Unit]
Description=Proxy that allows tcp connections to serial ports
After=syslog.target network.target

[Service]
Type=forking
ExecStart=/usr/local/bin/ser2sock -d
ExecReload=/bin/kill -HUP $MAINPID

[Install]
WantedBy=multi-user.target
```

**Comment by endlesscoil** [comment]
Thanks for the report!  

I've updated the configure scripts to use SSL_CTX_new instead of SSL_library_init.  Seems to support both OpenSSL 1.0 and 1.1.
